In [31]:
import pandas as pd
import glob 

annotators = [
    "../dataset_veronika",
    "../ukrainian_dataset",
]

annotator_dfs = {}
for i, annotator in enumerate(annotators):
    csv_files = glob.glob(f"{annotator}/*/*.csv")
    print(csv_files)
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        current_annotator_df = annotator_dfs.get(i, pd.DataFrame())
        annotator_dfs[i] = pd.concat([current_annotator_df, df], ignore_index=True)

['../dataset_veronika/test/_classes.csv', '../dataset_veronika/train/_classes.csv', '../dataset_veronika/valid/_classes.csv']
['../ukrainian_dataset/test/_classes.csv', '../ukrainian_dataset/train/_classes.csv', '../ukrainian_dataset/valid/_classes.csv']

In [32]:
import os 
for image_file in glob.glob("./ukrainian/images/*"):
    file_name = image_file.split("/")[-1].split("_jpg")[0]
    os.rename(image_file, f"./ukrainian/images/{file_name}")

In [33]:
import difflib


def get_label_mapping(current_labels, expected_labels, cutoff=0.8):
    label_mapping = {}
    for label in current_labels:
        if label == "No Propaganda":
            label_mapping[label] = "No Propaganda"
            continue
        matches = get_close_matches(label, expected_labels, n=1, cutoff=cutoff)
        if matches:
            label_mapping[label] = matches[0]
            expected_labels.remove(matches[0])
        else:
            label_mapping[label] = None

    return label_mapping

def get_close_matches(word : str, possibilities : list[str], n=1, cutoff=0.6):
    return difflib.get_close_matches(word, possibilities, n=n, cutoff=cutoff)

In [34]:
expected_labels = {'Appeal to (Strong) Emotions',
 'Appeal to authority',
 'Appeal to fear/prejudice',
 'Bandwagon',
 'Black-and-white Fallacy/Dictatorship',
 'Causal Oversimplification',
 'Doubt',
 'Exaggeration/Minimisation',
 'Flag-waving',
 'Glittering generalities (Virtue)',
 'Loaded Language',
 "Misrepresentation of Someone's Position (Straw Man)",
 'Name calling/Labeling',
 'Obfuscation, Intentional vagueness, Confusion',
 'Presenting Irrelevant Data (Red Herring)',
 'Reductio ad hitlerum',
 'Repetition',
 'Slogans',
 'Smears',
 'Thought-terminating cliché',
 'Transfer',
 'Whataboutism'}


old_to_new_label_mapping = get_label_mapping(list(annotator_dfs[0].iloc[:,1:].columns), expected_labels, cutoff=0.1)

In [35]:
old_to_new_label_mapping

{'Appeal to -Strong- Emotions': 'Appeal to (Strong) Emotions',
 'Appeal to fear-prejudice': 'Appeal to fear/prejudice',
 'Bandwagon': 'Bandwagon',
 'Black-and-white Fallacy-Dictatorship': 'Black-and-white Fallacy/Dictatorship',
 'Causal Oversimplification': 'Causal Oversimplification',
 'Doubt': 'Doubt',
 'Exaggeration-Minimisation': 'Exaggeration/Minimisation',
 'Flag-waving': 'Flag-waving',
 'Glittering generalities -Virtue-': 'Glittering generalities (Virtue)',
 'Loaded Language': 'Loaded Language',
 'Misrepresentation of Someones Position -Straw Man-': "Misrepresentation of Someone's Position (Straw Man)",
 'Name calling-Labeling': 'Name calling/Labeling',
 'No Propaganda': 'No Propaganda',
 'Obfuscation- Intentional vagueness- Confusion': 'Obfuscation, Intentional vagueness, Confusion',
 'Presenting Irrelevant Data -Red Herring-': 'Presenting Irrelevant Data (Red Herring)',
 'Reductio ad hitlerum': 'Reductio ad hitlerum',
 'Repetition': 'Repetition',
 'Slogans': 'Slogans',
 'Smears': 'Smears',
 'Thought-terminating cliche': 'Thought-terminating cliché',
 'Transfer': 'Transfer',
 'Unlabeled': 'Whataboutism',
 'Whataboutism': 'Appeal to authority'}

In [36]:
for annotator_df in annotator_dfs.values():
    annotator_df.rename(columns=old_to_new_label_mapping, inplace=True)

In [37]:
# prepare jsonl files for each annotator
import json

annotators_jsonl = []
for annotator_id, annotator_df in annotator_dfs.items():
    output_data = []
    columns = annotator_df.columns[1:]
    for _, row in annotator_df.iterrows():
        image_name = row[0].split("_jpg")[0]
        labels = columns[row[1:] == 1].tolist()
        output_data.append({
            "image": image_name,
            "labels": labels
        })

    annotators_jsonl.append(output_data)

/tmp/ipykernel_72010/1449656344.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  image_name = row[0].split("_jpg")[0]

In [38]:
df1 = pd.DataFrame.from_records(annotators_jsonl[0])
df2 = pd.DataFrame.from_records(annotators_jsonl[1])


annotators_df = df1.merge(df2, on="image", how="outer", suffixes=('_annotator1', '_annotator2'))
annotators_df.sort_values(by="image", inplace=True)
annotators_df[-30:]

,image,labels_annotator1,labels_annotator2
170,tg_5344,[No Propaganda],"[Causal Oversimplification, Transfer]"
171,tg_5345,[No Propaganda],"[Appeal to (Strong) Emotions, Loaded Language]"
172,tg_5346,"[Appeal to fear/prejudice, Causal Oversimplifi...","[Appeal to fear/prejudice, Causal Oversimplifi..."
173,tg_5347,"[Exaggeration/Minimisation, Flag-waving]","[Exaggeration/Minimisation, Flag-waving, Loade..."
174,tg_5349,[No Propaganda],[No Propaganda]
175,tg_5350,"[Appeal to (Strong) Emotions, Black-and-white ...","[Appeal to (Strong) Emotions, Causal Oversimpl..."
176,tg_5351,[No Propaganda],[No Propaganda]
177,tg_5352,[No Propaganda],[No Propaganda]
178,tg_5353,[No Propaganda],[No Propaganda]
179,tg_5354,[No Propaganda],[No Propaganda]
180,tg_5355,[No Propaganda],[No Propaganda]
181,tg_5357,[No Propaganda],[No Propaganda]
182,tg_5358,"[Exaggeration/Minimisation, Flag-waving]","[Exaggeration/Minimisation, Flag-waving, Glitt..."
183,tg_5359,[No Propaganda],[No Propaganda]
184,tg_5360,[No Propaganda],[No Propaganda]
185,tg_5361,[No Propaganda],[No Propaganda]
186,tg_5362,[No Propaganda],"[Appeal to (Strong) Emotions, Exaggeration/Min..."
187,tg_5364,[No Propaganda],"[Causal Oversimplification, Exaggeration/Minim..."
188,tg_5365,"[Appeal to fear/prejudice, Bandwagon, Flag-wav...","[Bandwagon, Flag-waving]"
189,tg_5366,"[Appeal to fear/prejudice, Black-and-white Fal...","[Exaggeration/Minimisation, Flag-waving, Smears]"
190,tg_5369,[No Propaganda],[No Propaganda]
191,tg_5370,[No Propaganda],[No Propaganda]
192,tg_5371,[No Propaganda],[Exaggeration/Minimisation]
193,tg_5372,[No Propaganda],[No Propaganda]
194,tg_5373,[No Propaganda],[Exaggeration/Minimisation]
195,tg_5374,[No Propaganda],[No Propaganda]
196,tg_5375,[No Propaganda],[Appeal to (Strong) Emotions]
197,tg_5376,[No Propaganda],[No Propaganda]
198,tg_5379,[No Propaganda],[No Propaganda]
199,tg_5380,[No Propaganda],[No Propaganda]

In [39]:
annotators_df.to_csv("/home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/annotators.csv", index=False)

In [40]:
#out format
#{"id": "858_batch_2", "labels": ["Flag-waving", "Transfer"], "text": "ВИБОРИ 2020: ОБЕРИ ФАКЕЛ", "image": "858_image_batch_2.png"}
#
with open('./ukrainian/raw/images_data.json','r') as f:
    data = json.load(f)

data
get_file_name = lambda x: x.split("/")[-1]
data = [{'text': item['text'], 'image': get_file_name(item['path'])} for item in data]

In [41]:
annotations = sorted(annotators_jsonl[0], key=lambda x: x['image'])
data  = sorted(data, key=lambda x: x['image'])

In [42]:
results = []
for annotation, item in zip(annotations, data):
    results.append({
        "id": item['image'].split(".")[0],
        "labels": annotation['labels'],
        "text": item['text'],
        "image": item['image']
    })

In [43]:
results

[{'id': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig',
  'labels': ['Smears'],
  'text': 'Бойові виходи за лінію фронту',
  'image': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig.jpg'},
 {'id': 'csv_10nuP18xGKwhwzie8LQg1jJvQ7sEyBUNk',
  'labels': ['Whataboutism'],
  'text': 'Невідомий художник. Дівчина з тараканами. -- Геніальна ідея! Українці повністю підтримають! Симоньян пропонує "здійснити ядерний вибух десь над Сибіром"',
  'image': 'csv_10nuP18xGKwhwzie8LQg1jJvQ7sEyBUNk.jpg'},
 {'id': 'csv_11FXDzESQrZpC5yqpUrKbsipXldf1owRH',
  'labels': ['Causal Oversimplification', 'Smears'],
  'text': '- Німеччина передає ЗРК Patriot. - На наступний день хтось збиває метеорит. - Хлопці *не тицяли ту кнопку*.',
  'image': 'csv_11FXDzESQrZpC5yqpUrKbsipXldf1owRH.jpg'},
 {'id': 'csv_12eKY_11DKhS3OJkRBe3Ik-w6IF0XoKHP',
  'labels': ['Doubt', 'Smears'],
  'text': 'Сьогодні побачимо, як працює 5 стаття Статуту NATO?',
  'image': 'csv_12eKY_11DKhS3OJkRBe3Ik-w6IF0XoKHP.jpg'},
 {'id': 'csv_12vuewEZ3Dv50-FjDlCv4RFJpRr-EhPNZ',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Smears'],
  'text': 'Пропаганда - росіяни - російські медіа.',
  'image': 'csv_12vuewEZ3Dv50-FjDlCv4RFJpRr-EhPNZ.jpg'},
 {'id': 'csv_15Xl8UwDt1ZSFTNyzlZN6fMHpXEpYHQCk',
  'labels': ['Causal Oversimplification', 'Exaggeration/Minimisation'],
  'text': 'Коли ледве заснув о 4:30, та через годину прокинувся через повітряну тривогу. - Я зараз ті ракети путіну в сраку запхну',
  'image': 'csv_15Xl8UwDt1ZSFTNyzlZN6fMHpXEpYHQCk.jpg'},
 {'id': 'csv_15Z8Rt1Ota8wub2hqnuiUIItFFPqsrPH5',
  'labels': ['Exaggeration/Minimisation', 'Smears'],
  'text': 'Pуцка армія в тілівізорі - руцка армія в житті',
  'image': 'csv_15Z8Rt1Ota8wub2hqnuiUIItFFPqsrPH5.jpg'},
 {'id': 'csv_16iNP31Z76-aUG4_3v2dVQXT6-vl5WvrT',
  'labels': ['No Propaganda'],
  'text': 'ракети з боліт — офігенні ППО — будильник на роботу',
  'image': 'csv_16iNP31Z76-aUG4_3v2dVQXT6-vl5WvrT.jpg'},
 {'id': 'csv_17b2FLR8lRzXZV1EltJ_trlu_4oY3K9Ix',
  'labels': ['Appeal to fear/prejudice',
   'Causal Oversimplification',
   'Loaded Language',
   'Name calling/Labeling'],
  'text': 'щасливі новоросійцовци, в черзі за бензином, дивляться як местное пво лупить по домах намагаючись попасти в українські дрони',
  'image': 'csv_17b2FLR8lRzXZV1EltJ_trlu_4oY3K9Ix.jpg'},
 {'id': 'csv_17nYn-o-TfP0HMVFYfiNE-VJxOWFH-QGE',
  'labels': ['Appeal to (Strong) Emotions', 'Loaded Language', 'Transfer'],
  'text': 'В дупу засуньте свої ракети',
  'image': 'csv_17nYn-o-TfP0HMVFYfiNE-VJxOWFH-QGE.jpg'},
 {'id': 'csv_17voh_B-0ayn2K7k-KbPZrGaFQG16qcyD',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Smears',
   'Transfer'],
  'text': 'Російський військовий парад 9 травня',
  'image': 'csv_17voh_B-0ayn2K7k-KbPZrGaFQG16qcyD.jpg'},
 {'id': 'csv_187mz_-6PYDq6npL3VY9WfQTUzQ9TvlNW',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Slogans'],
  'text': 'Ремонт мостів будь-якої складності: швидко та якісно',
  'image': 'csv_187mz_-6PYDq6npL3VY9WfQTUzQ9TvlNW.jpg'},
 {'id': 'csv_18prs6s39jUFeFR3GkzP3oL3Z1TAloAhZ',
  'labels': ['Repetition', 'Smears', 'Transfer'],
  'text': 'Хехехе я тобі напиздів, розумієш, напиздюнькав, наїбав, викупаєш блять, я тобі набрехав нахуй, я сказав тобі неправду',
  'image': 'csv_18prs6s39jUFeFR3GkzP3oL3Z1TAloAhZ.jpg'},
 {'id': 'csv_18qlkKB9RLb7J0U35PGDKl1kXQC6gOXr0',
  'labels': ['No Propaganda'],
  'text': 'Напевно, знову думає про своїх баб',
  'image': 'csv_18qlkKB9RLb7J0U35PGDKl1kXQC6gOXr0.jpg'},
 {'id': 'csv_19K52HV_zp2kq13WfLeMBNkm3428uyUwY',
  'labels': ['Appeal to (Strong) Emotions'],
  'text': 'вони вже пагаварили? -- не ... тікі збираюцця -- та бляяяя',
  'image': 'csv_19K52HV_zp2kq13WfLeMBNkm3428uyUwY.jpg'},
 {'id': 'csv_1A-cihVsP7tu8VHPba7zRWkUujJ00W-qc',
  'labels': ["Misrepresentation of Someone's Position (Straw Man)",
   'Smears',
   'Transfer'],
  'text': 'Кіт Келлог дивиться як працює київське ППО',
  'image': 'csv_1A-cihVsP7tu8VHPba7zRWkUujJ00W-qc.jpg'},
 {'id': 'csv_1AKtnUcdUIeNVze0-Rs_oe0rY7LEEjclO',
  'labels': ['Black-and-white Fallacy/Dictatorship'],
  'text': 'Путін здох! - Путін не здох! - Царев на підході',
  'image': 'csv_1AKtnUcdUIeNVze0-Rs_oe0rY7LEEjclO.jpg'},
 {'id': 'csv_1Al9-s0JO2cbXxCDkeWdpsZXGodrOxTIZ',
  'labels': ['Flag-waving', 'Reductio ad hitlerum', 'Slogans'],
  'text': "1939-1945.  Пам'ятаємо, перемагаємо. Перемогли нацизм – переможемо i рашизм!",
  'image': 'csv_1Al9-s0JO2cbXxCDkeWdpsZXGodrOxTIZ.jpg'},
 {'id': 'csv_1Bnkw2vdtnEpGhXKOvLI4FbN0rmogd6_L',
  'labels': ['Appeal to (Strong) Emotions', 'Causal Oversimplification'],
  'text': 'Ти ж хочеш мати бронь, по догляду?!!!!',
  'image': 'csv_1Bnkw2vdtnEpGhXKOvLI4FbN0rmogd6_L.jpg'},
 {'id': 'csv_1BpTThdNzKWJL4HV99MPnQFprzaAEYYPI',
  'labels': ['Glittering generalities (Virtue)', 'Smears', 'Transfer'],
  'text': 'Лади нема, можемо дати Ford.',
  'image': 'csv_1BpTThdNzKWJL4HV99MPnQFprzaAEYYPI.jpg'},
 {'id': 'csv_1BxH9gv_9C3sGTrtvSJOD5olLRrRS5j55',
  'labels': ['Exaggeration/Minimisation',
   "Misrepresentation of Someone's Position (Straw Man)",
   'Reductio ad hitlerum'],
  'text': 'Знову про свого Путіна думає -- *наскорочував терміни та спить',
  'image': 'csv_1BxH9gv_9C3sGTrtvSJOD5olLRrRS5j55.jpg'},
 {'id': 'csv_1CEAEC2XjcetNmkCJVYpb619Jw2hrGb0z',
  'labels': ['Exaggeration/Minimisation',
   'Obfuscation, Intentional vagueness, Confusion',
   'Smears'],
  'text': 'Румунія просить збивати шахеди, що летять до них. — От ви зараз серйозно?',
  'image': 'csv_1CEAEC2XjcetNmkCJVYpb619Jw2hrGb0z.jpg'},
 {'id': 'csv_1DbVrsaLVp810zGm7Zsb6UOz78wo99ws6',
  'labels': ['Appeal to (Strong) Emotions', 'Transfer'],
  'text': 'Мені нравиться як воно горить - люди бігають, суїтяться...',
  'image': 'csv_1DbVrsaLVp810zGm7Zsb6UOz78wo99ws6.jpg'},
 {'id': 'csv_1DtfA0h_xVyHPGp2LrNFyXpLdDiA8uaHs',
  'labels': ["Misrepresentation of Someone's Position (Straw Man)", 'Smears'],
  'text': 'А потім Саліван і каже - як воскреснеш то скажи українцям, щоб не бомбили НПЗ',
  'image': 'csv_1DtfA0h_xVyHPGp2LrNFyXpLdDiA8uaHs.jpg'},
 {'id': 'csv_1EIwGJLc46qa_HtqG0-D8lfiIPOEsY5yj',
  'labels': ['Causal Oversimplification', 'Exaggeration/Minimisation'],
  'text': 'Китай виступив проти розміщення ядерної зброї РФ у Білорусі, M3C KHP.',
  'image': 'csv_1EIwGJLc46qa_HtqG0-D8lfiIPOEsY5yj.jpg'},
 {'id': 'csv_1EL8Cx39fzHx9mKk8Z8W20EX-LxZ_bbo6',
  'labels': ['Appeal to (Strong) Emotions',
   'Appeal to fear/prejudice',
   'Causal Oversimplification'],
  'text': 'Трохи не дійшли до Києва',
  'image': 'csv_1EL8Cx39fzHx9mKk8Z8W20EX-LxZ_bbo6.jpg'},
 {'id': 'csv_1EY1F7cXlt3ZqTFnhcHp5XX0W4gSO9CIg',
  'labels': ['Exaggeration/Minimisation',
   'Obfuscation, Intentional vagueness, Confusion'],
  'text': 'Продам червону цеглу! У необмеженій кількості. Звертатись за адресою: Москва. Кремль. Самовивіз!',
  'image': 'csv_1EY1F7cXlt3ZqTFnhcHp5XX0W4gSO9CIg.jpg'},
 {'id': 'csv_1Eh0yJjnRzEgsXztrEM1hNWObMt6Y1He8',
  'labels': ['No Propaganda'],
  'text': 'Козеріг: якщо ви усміхаєтесь, це ще не означає, що вам смішно',
  'image': 'csv_1Eh0yJjnRzEgsXztrEM1hNWObMt6Y1He8.jpg'},
 {'id': 'csv_1GR49wqoB36kABB3vL0ieq1o1pSSAlbjg',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Glittering generalities (Virtue)'],
  'text': 'росіяни: на 10й день нарешті погасили пожежу на нафтобазі в ростовській області. українські далекобійні дрони: - Хочете прікол?',
  'image': 'csv_1GR49wqoB36kABB3vL0ieq1o1pSSAlbjg.jpg'},
 {'id': 'csv_1GzS_S7cgzxFq2HL2CnTRjMf_g6PTQdel',
  'labels': ['Bandwagon'],
  'text': '— може я теж хочу томагавку',
  'image': 'csv_1GzS_S7cgzxFq2HL2CnTRjMf_g6PTQdel.jpg'},
 {'id': 'csv_1HRwYq0KqqgXguVWAmIph9E3wKK_Pw8Zr',
  'labels': ['Exaggeration/Minimisation', 'Smears'],
  'text': 'павутина -- Дональд Трамп продемонстрував план операції "ПАВУТИНА", який він особисто ухвалив ще два роки тому!',
  'image': 'csv_1HRwYq0KqqgXguVWAmIph9E3wKK_Pw8Zr.jpg'},
 {'id': 'csv_1HkWMf3hpyboOpJufpFba9-xsOTRQ4nQy',
  'labels': ['Exaggeration/Minimisation',
   "Misrepresentation of Someone's Position (Straw Man)",
   'Smears'],
  'text': 'Щастя – це знайти людину, яка тримається за себе, як Шольц за „леопарди“',
  'image': 'csv_1HkWMf3hpyboOpJufpFba9-xsOTRQ4nQy.jpg'},
 {'id': 'csv_1HuQzlULlLW5pzaxyNSo4AFZZVzZOBCGM',
  'labels': ['Appeal to fear/prejudice'],
  'text': 'Два метры мiцного бетону тобi зверху',
  'image': 'csv_1HuQzlULlLW5pzaxyNSo4AFZZVzZOBCGM.jpg'},
 {'id': 'csv_1I59sHCS5OY4zUxs-g4nS4ttxaIj3_ihL',
  'labels': ['Exaggeration/Minimisation',
   'Loaded Language',
   'Obfuscation, Intentional vagueness, Confusion'],
  'text': 'Пам\'ятник "Володимир Ленін засновує Україну". Бронза, граніт, альцгеймер',
  'image': 'csv_1I59sHCS5OY4zUxs-g4nS4ttxaIj3_ihL.jpg'},
 {'id': 'csv_1Ioe_jk2gwxssv0PcOaHJm1C_VxeZRgLb',
  'labels': ['Repetition', 'Smears'],
  'text': '2022: "НАТО, закрийте небо над Україною!" -- 2025: "НАТО, закрийте небо хоч над собою!"',
  'image': 'csv_1Ioe_jk2gwxssv0PcOaHJm1C_VxeZRgLb.jpg'},
 {'id': 'csv_1IuI1-MTnUctPpWVuM9GUU4XB3Ht7p5r6',
  'labels': ['Appeal to (Strong) Emotions',
   'Glittering generalities (Virtue)'],
  'text': 'Хочеться філіжанку кави і якусь масову трагедію в росіі',
  'image': 'csv_1IuI1-MTnUctPpWVuM9GUU4XB3Ht7p5r6.jpg'},
 {'id': 'csv_1J5RRuMM79ql_f7fNFT7dipg38APC93Z8',
  'labels': ['Appeal to (Strong) Emotions',
   'Obfuscation, Intentional vagueness, Confusion',
   'Transfer'],
  'text': 'Я вам що, кіллер?',
  'image': 'csv_1J5RRuMM79ql_f7fNFT7dipg38APC93Z8.jpg'},
 {'id': 'csv_1JdqvIa3Dn9Xan87wvOAOgpNMsbmvzDxh',
  'labels': ['Flag-waving', 'Glittering generalities (Virtue)'],
  'text': '07.06.2025 (10.00) -- збито: -винищувач Су-35',
  'image': 'csv_1JdqvIa3Dn9Xan87wvOAOgpNMsbmvzDxh.jpg'},
 {'id': 'csv_1KTez4UC5TqRrSw4-RsEbEgeMUymlZTNR',
  'labels': ['Appeal to (Strong) Emotions', 'Exaggeration/Minimisation'],
  'text': 'Українець зранку іде на роботу',
  'image': 'csv_1KTez4UC5TqRrSw4-RsEbEgeMUymlZTNR.jpg'},
 {'id': 'csv_1KXdSpbH06J7508iSvl9xeRvbZ3vXhF3E',
  'labels': ['Appeal to (Strong) Emotions', 'Flag-waving'],
  'text': 'Повітряна тривога',
  'image': 'csv_1KXdSpbH06J7508iSvl9xeRvbZ3vXhF3E.jpg'},
 {'id': 'csv_1LD3SuCeT94e6Im6xOwK6XlUPctIeOd7H',
  'labels': ['Causal Oversimplification', 'Smears'],
  'text': '- Наступ буде з Ненацька!!! - А де це??? -- Ненацьк -- Ненацьк -- Ненацьк',
  'image': 'csv_1LD3SuCeT94e6Im6xOwK6XlUPctIeOd7H.jpg'},
 {'id': 'csv_1NDx7AeW1Y_ELMUi2sJLLEHxu2M79WOLh',
  'labels': ['Appeal to (Strong) Emotions', 'Exaggeration/Minimisation'],
  'text': 'Українці масово сумують із-за пожежі в Ростові',
  'image': 'csv_1NDx7AeW1Y_ELMUi2sJLLEHxu2M79WOLh.jpg'},
 {'id': 'csv_1OhLqfzHgovovA_2eZwke71-Os3u7kLhe',
  'labels': ['Appeal to (Strong) Emotions'],
  'text': 'Україна отримуватиме ракети АТАCMS на постійній основі, - Кулеба',
  'image': 'csv_1OhLqfzHgovovA_2eZwke71-Os3u7kLhe.jpg'},
 {'id': 'csv_1P2ntPlLGHd9lhDg52WH9r6k0BLQ2Hqgv',
  'labels': ['Appeal to (Strong) Emotions',
   'Appeal to fear/prejudice',
   'Obfuscation, Intentional vagueness, Confusion'],
  'text': 'Мамо, я поїв і в шапці',
  'image': 'csv_1P2ntPlLGHd9lhDg52WH9r6k0BLQ2Hqgv.jpg'},
 {'id': 'csv_1Py92xnYDI5ilr30qKDF1GIIx9ftRV5h-',
  'labels': ['Exaggeration/Minimisation'],
  'text': 'Зеленський -- путін: та нє, я їбав',
  'image': 'csv_1Py92xnYDI5ilr30qKDF1GIIx9ftRV5h-.jpg'},
 {'id': 'csv_1QOtqqVGS9dXu17pwVMP2gC-KW8yY5BC-',
  'labels': ['Causal Oversimplification',
   "Misrepresentation of Someone's Position (Straw Man)",
   'Appeal to authority'],
  'text': 'Трамп дозволив далекобійні удари по Росії – Келлог. - Дозволяю - а томагавки?',
  'image': 'csv_1QOtqqVGS9dXu17pwVMP2gC-KW8yY5BC-.jpg'},
 {'id': 'csv_1RDsny5mL3po66GY0R1OL3tHpUUD2XcqV',
  'labels': ['Exaggeration/Minimisation', 'Smears', 'Transfer'],
  'text': '- години тут дорівнюють вічності в Україні – що це за планета? – Трампиздурій',
  'image': 'csv_1RDsny5mL3po66GY0R1OL3tHpUUD2XcqV.jpg'},
 {'id': 'csv_1Ro8yHsRhKCGJ2A96cLJKCZzVXnwu5bhK',
  'labels': ['Appeal to fear/prejudice',
   'Causal Oversimplification',
   'Exaggeration/Minimisation'],
  'text': 'Браслет, що перетворює русофобію на енергію -- Українці',
  'image': 'csv_1Ro8yHsRhKCGJ2A96cLJKCZzVXnwu5bhK.jpg'},
 {'id': 'csv_1SKjQSE5W5hwfdKP2jmnp5_bOABLbDhti',
  'labels': ['Appeal to fear/prejudice',
   'Glittering generalities (Virtue)',
   'Smears'],
  'text': 'Черноморский Флот РФ. Остатки.  - Прівєт! Які ви красіві, підсмажені! теж до вас хочемо! Сергей Котов, Оленегорский горняк, Саратов, Цезар Кунніков, Адмирал Макаров, Крейсер Москва, Новочеркасск',
  'image': 'csv_1SKjQSE5W5hwfdKP2jmnp5_bOABLbDhti.jpg'},
 {'id': 'csv_1T7NIuVIHZ5gDHPSGuKBPyEFtWmkuajWv',
  'labels': ['Flag-waving'],
  'text': 'Костюм? Наступного разу вдягну щоб спалити мацкву',
  'image': 'csv_1T7NIuVIHZ5gDHPSGuKBPyEFtWmkuajWv.jpg'},
 {'id': 'csv_1TNiTmru80wiijeumkbH88TwkatJE9iTO',
  'labels': ['Causal Oversimplification', 'Smears'],
  'text': 'Вбийте царя. Царя! Не Царьова',
  'image': 'csv_1TNiTmru80wiijeumkbH88TwkatJE9iTO.jpg'},
 {'id': 'csv_1TSEs2hikRGquY_AMVGppnOtwWoEtokTo',
  'labels': ['Black-and-white Fallacy/Dictatorship',
   'Exaggeration/Minimisation'],
  'text': 'Очікування на звернення питуна перед 24.02 -- Очікування на звернення питуна зараз',
  'image': 'csv_1TSEs2hikRGquY_AMVGppnOtwWoEtokTo.jpg'},
 {'id': 'csv_1UTsSKtviwlAP0yIT6U5hbn1oTUgZsV46',
  'labels': ['Exaggeration/Minimisation'],
  'text': 'Весь світ -- Українці',
  'image': 'csv_1UTsSKtviwlAP0yIT6U5hbn1oTUgZsV46.jpg'},
 {'id': 'csv_1XBuNPKrtwzfktJJ7CKICo2AOcA7zowmr',
  'labels': ['Appeal to fear/prejudice', 'Exaggeration/Minimisation'],
  'text': "Президент підписав закон про направлення ЗСУ до інших держав -- ПМР Придністров'я",
  'image': 'csv_1XBuNPKrtwzfktJJ7CKICo2AOcA7zowmr.jpg'},
 {'id': 'csv_1YDUwDv-RyzmWv_Oq6v9qOJgBR2_SwFxj',
  'labels': ['Name calling/Labeling', 'Smears'],
  'text': 'Українці знову жодного разу мені не подякували? — А іще називають тебе хробаком і штопаним гандьоном!',
  'image': 'csv_1YDUwDv-RyzmWv_Oq6v9qOJgBR2_SwFxj.jpg'},
 {'id': 'csv_1YosMGReMhHOopEF0QYNvsLvbMdfolLTt',
  'labels': ['Appeal to fear/prejudice', 'Transfer'],
  'text': 'Ми знайдемо кожну сволоту, яка бомбила нашу землю',
  'image': 'csv_1YosMGReMhHOopEF0QYNvsLvbMdfolLTt.jpg'},
 {'id': 'csv_1Z7YxQ36i1QBhEuQxmBUZ3HxnGFxPYExt',
  'labels': ['Causal Oversimplification',
   'Exaggeration/Minimisation',
   'Slogans'],
  'text': 'Демонтаж мостів, будівель та техніки, будь-якої складності! Швидко та якісно...',
  'image': 'csv_1Z7YxQ36i1QBhEuQxmBUZ3HxnGFxPYExt.jpg'},
 {'id': 'csv_1ZABEopY4DTFtorKIJHfb8X2tHImu9WdK',
  'labels': ['Exaggeration/Minimisation', 'Smears'],
  'text': 'Це і була "потужна" заява Трампа? І "потужні" санкції?',
  'image': 'csv_1ZABEopY4DTFtorKIJHfb8X2tHImu9WdK.jpg'},
 {'id': 'csv_1ZKQcOIwyPXIALb2riK8uMuqAkn7rvKgu',
  'labels': ['Black-and-white Fallacy/Dictatorship',
   'Presenting Irrelevant Data (Red Herring)'],
  'text': 'ЩЗХ?? Робін Гуд підтримав контрнаступ??',
  'image': 'csv_1ZKQcOIwyPXIALb2riK8uMuqAkn7rvKgu.jpg'},
 {'id': 'csv_1ZUuniQI-iaZ1mfd3wdvdsOP9Zr3mR5KB',
  'labels': ['Name calling/Labeling'],
  'text': 'Знищено російський великий десантний корабель "Новочеркаськ". - "Перекваліфіковано" у підводний човен)))',
  'image': 'csv_1ZUuniQI-iaZ1mfd3wdvdsOP9Zr3mR5KB.jpg'},
 {'id': 'csv_1_0CmY6hnHGdORcJaKmRigKUEYdkqe34X',
  'labels': ['Black-and-white Fallacy/Dictatorship', 'Flag-waving'],
  'text': 'Ця війна має два варіанти: або Україна переможе, або росія програє',
  'image': 'csv_1_0CmY6hnHGdORcJaKmRigKUEYdkqe34X.jpg'},
 {'id': 'csv_1_lV1UhJjYzDZ4y4zVde_I4Z9l34fhe3b',
  'labels': ['Smears', 'Transfer'],
  'text': 'Єгипет, III ст. до н.э., статуя Бога Пиздабольства.',
  'image': 'csv_1_lV1UhJjYzDZ4y4zVde_I4Z9l34fhe3b.jpg'},
 {'id': 'csv_1aVzq0hNJM79ubHW9pVj1dRko9h418U4G',
  'labels': ['Presenting Irrelevant Data (Red Herring)'],
  'text': 'З боку України знову летять -- Шахеди? -- Підйоби',
  'image': 'csv_1aVzq0hNJM79ubHW9pVj1dRko9h418U4G.jpg'},
 {'id': 'csv_1bydWAdq0PijW8t3sPZEiQADZaaKDyVDk',
  'labels': ['Obfuscation, Intentional vagueness, Confusion', 'Smears'],
  'text': 'Пасажир з Москви забув в аеропорту Пекіна доволі дивний чемоданчик',
  'image': 'csv_1bydWAdq0PijW8t3sPZEiQADZaaKDyVDk.jpg'},
 {'id': 'csv_1cmjkZ8nBDuRrOEk4CzrF69nLdbIOw_yK',
  'labels': ['Appeal to (Strong) Emotions',
   'Causal Oversimplification',
   'Loaded Language',
   'Thought-terminating cliché'],
  'text': '"Повітряна тривога"! — Трохи заїб@ло жити в непрості та цікаві часи...',
  'image': 'csv_1cmjkZ8nBDuRrOEk4CzrF69nLdbIOw_yK.jpg'},
 {'id': 'csv_1dCdvDnBfu5F0Fb8Ph4r-TnUDiH_pwBUU',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Slogans'],
  'text': 'Частково мобілізовані росіяни скоро повернуться додому! ...частково...',
  'image': 'csv_1dCdvDnBfu5F0Fb8Ph4r-TnUDiH_pwBUU.jpg'},
 {'id': 'csv_1e5Xg2iMyrkPIzXIQ2fAwJtpLGGEzXfUg',
  'labels': ['No Propaganda'],
  'text': 'Пункт незламності. Інтернет, тепло, вода.',
  'image': 'csv_1e5Xg2iMyrkPIzXIQ2fAwJtpLGGEzXfUg.jpg'},
 {'id': 'csv_1fBuUvrNVjrskjP7Dq8pXLptssX-FcROp',
  'labels': ['Appeal to fear/prejudice'],
  'text': 'Повістка',
  'image': 'csv_1fBuUvrNVjrskjP7Dq8pXLptssX-FcROp.jpg'},
 {'id': 'csv_1gN6EzJKrA2ggHmp35boJp-1GFvqNsFzS',
  'labels': ['Appeal to (Strong) Emotions',
   'Glittering generalities (Virtue)'],
  'text': 'я обожнюю зранку запах чогось розйобаного на росії.',
  'image': 'csv_1gN6EzJKrA2ggHmp35boJp-1GFvqNsFzS.jpg'},
 {'id': 'csv_1gQKDFVCmsA5DKq5gxO_QQ3xCwTdMZoIu',
  'labels': ['Smears'],
  'text': 'Дмитро ИПСОн',
  'image': 'csv_1gQKDFVCmsA5DKq5gxO_QQ3xCwTdMZoIu.jpg'},
 {'id': 'csv_1gbSn5MqWtjgVlG6bqVB-ul9FSRMRdu6r',
  'labels': ['Appeal to fear/prejudice',
   'Obfuscation, Intentional vagueness, Confusion'],
  'text': 'шось цьогорічний парад пабєди якийсь скучний -- ооо, так краще',
  'image': 'csv_1gbSn5MqWtjgVlG6bqVB-ul9FSRMRdu6r.jpg'},
 {'id': 'csv_1h8DQF6VfAKCrSzMXoisCLwCjSZ85V290',
  'labels': ['Black-and-white Fallacy/Dictatorship',
   'Glittering generalities (Virtue)'],
  'text': '- Привіт, я Бан Чан - I шо? - Доброго ранку, ми з України - Вiталiй Кiм!!',
  'image': 'csv_1h8DQF6VfAKCrSzMXoisCLwCjSZ85V290.jpg'},
 {'id': 'csv_1hH1wRVhdXOc_ZtpxdtsQa0ekVqbEnYaU',
  'labels': ['Appeal to (Strong) Emotions',
   'Causal Oversimplification',
   'Transfer'],
  'text': 'Сусіди обговорюють можливість мирних переговорів із Росією, коли немає світла.',
  'image': 'csv_1hH1wRVhdXOc_ZtpxdtsQa0ekVqbEnYaU.jpg'},
 {'id': 'csv_1iwnE7hXJTYA9HWGsN3GXZrtLSXgHcBkH',
  'labels': ['Appeal to fear/prejudice',
   'Exaggeration/Minimisation',
   'Flag-waving'],
  'text': 'Роснявий солдат, коли побачив азовця',
  'image': 'csv_1iwnE7hXJTYA9HWGsN3GXZrtLSXgHcBkH.jpg'},
 {'id': 'csv_1jWv14cplK9_nuP43CjZvKKiTpS4XtY4Q',
  'labels': ['Bandwagon',
   'Black-and-white Fallacy/Dictatorship',
   'Flag-waving'],
  'text': 'iPad Pro. 58 000 грн. 1 ТБ пам’яті. Можливість виконувати купу задач. Є можливість встановити російську мову. — Магнітна дошка. 1 700 грн. 0 байт пам’яті. Тупо малювалка їбать. Російська мова відсутня повністю. Вибiр очевидний.',
  'image': 'csv_1jWv14cplK9_nuP43CjZvKKiTpS4XtY4Q.jpg'},
 {'id': 'csv_1l8l3iqfdMTzYPRmIdVwhoVpbz4DoH-jk',
  'labels': ['Appeal to (Strong) Emotions', 'Name calling/Labeling'],
  'text': 'Русня: - Ми виключiлi украiнцам свет. Українцi: - Цип-цип-цип',
  'image': 'csv_1l8l3iqfdMTzYPRmIdVwhoVpbz4DoH-jk.jpg'},
 {'id': 'csv_1lEnZjL4F2uvx1q2eHg9Zx6415aylzrGN',
  'labels': ['Appeal to fear/prejudice', 'Smears', 'Transfer'],
  'text': 'Руска опозиція тоді -- Руска опозиція зараз',
  'image': 'csv_1lEnZjL4F2uvx1q2eHg9Zx6415aylzrGN.jpg'},
 {'id': 'csv_1lMoiQisGNoT4zH7qDk351OPWuEu9jsKb',
  'labels': ['Appeal to (Strong) Emotions',
   'Exaggeration/Minimisation',
   'Glittering generalities (Virtue)'],
  'text': 'Дрони атакують Москву: вибухи, пожежі та колапс в аеропортах',
  'image': 'csv_1lMoiQisGNoT4zH7qDk351OPWuEu9jsKb.jpg'},
 {'id': 'csv_1m2InmrfXrSWegSA2fkfya4lv_0_0kqVL',
  'labels': ['Appeal to fear/prejudice',

In [46]:
import base64
import requests
import json
from openai import OpenAI
import time 

IMAGE_PATH = "../datasets/propaganda_950/images/1_image.png"

client = OpenAI(
    api_key="EMPTY",
    base_url="http://localhost:8000/v1",
    timeout=3600
)

def inference_model(prompt, image_path):
    # Load image & base64 encode
    with open(image_path, "rb") as f:
        image_bytes = f.read()

    image_b64 = base64.b64encode(image_bytes).decode("utf-8")

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image_url", 
                 "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"},
                    },
                {
                    "type": "text",
                    "text": prompt
                }
            ]
        }
    ]

    response = client.chat.completions.create(
        model="Qwen/Qwen3-VL-8B-Instruct-FP8",
        messages=messages,
        max_tokens=2048
    )
    return response.choices[0].message.content

prompt = "Describe the image in detail."
start = time.time()
response = inference_model(prompt, IMAGE_PATH)

print(f"Response costs: {time.time() - start:.2f}s")
print(f"Generated text: {response}")

Response costs: 16.39s
Generated text: This image is a political infographic designed as a side-by-side comparison, contrasting economic performance during the presidencies of Barack Obama and Donald Trump. It uses contrasting colors, text, and imagery to present its claims.

The image is divided vertically into two equal halves.

**Left Side: "8 YEARS UNDER OBAMA"**
*   **Header:** The top section has a dark gray background with the white text "8 YEARS UNDER OBAMA".
*   **Image:** Below the header is a photograph of President Barack Obama, looking serious and slightly to his right. He is wearing a dark suit, white shirt, and a red patterned tie.
*   **Data Boxes (Red Background, White Text):** Three red rectangular boxes are stacked vertically below the image, presenting negative economic figures:
    *   "4 MILLION JOBS LOST"
    *   "UNEMPLOYMENT PEAKED TO 9.9%"
    *   "GDP DOWN 2.8%"

**Right Side: "2 ½ YEARS UNDER TRUMP"**
*   **Header:** The top section has a black background with the white text "2 ½ YEARS UNDER TRUMP".
*   **Image:** Below the header is a photograph of President Donald Trump, smiling broadly and looking slightly to his left. He is wearing a dark suit, white shirt, and a bright red tie. The background appears to be a city skyline at night.
*   **Data Boxes (Green Background, White Text):** Three green rectangular boxes are stacked vertically below the image, presenting positive economic figures:
    *   "5.1 MILLION JOBS GAINED"
    *   "UNEMPLOYMENT FELL TO 3.6%"
    *   "GDP UP 3.2%"

**Overall Design and Intent:**
The infographic uses a stark visual contrast: red for the Obama side (associated with negative outcomes) and green for the Trump side (associated with positive outcomes). The layout is designed to be immediately readable and to create a strong impression of a "before and after" scenario, suggesting that Trump's shorter term was more economically successful than Obama's longer term. The use of large, bold text emphasizes the key statistics. It is clearly intended to be a piece of political commentary or propaganda.

In [47]:
prompt = """
You are OCR assistant. Your task is to extract text from the image and provide it in the output.
Please provide only text that is on the image. If no text is present, respond with 'No_text'.

Text on the image: 
"""

In [48]:
from tqdm import tqdm
for item in tqdm(results):
    image_path = f"./ukrainian/images/{item['image']}"
    if item['text'].strip().lower() == "unknown":
        ocr_text = inference_model(prompt, image_path)
        if ocr_text.strip().lower() != "no_text":
            item['text'] = ocr_text

100%|██████████| 200/200 [02:06<00:00,  1.58it/s]

In [49]:
results[0]

{'id': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig',
 'labels': ['Smears'],
 'text': 'Бойові виходи за лінію фронту',
 'image': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig.jpg'}

In [53]:
# ── Parse final labels from adjudicator CSV ──────────────────────────────────
final_csv_path = "/home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/annotators - annotators.csv"
orig_csv_path = "/home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/annotators.csv"

orig_df = pd.read_csv(orig_csv_path)
final_df = pd.read_csv(final_csv_path)

# image_N.jpg → real image name (same row order)
image_name_to_real = dict(zip(final_df["image"], orig_df["image"]))

import csv as csv_mod

def parse_final_labels(final_str):
    s = str(final_str).strip()
    if not s or s == "No Propaganda" or s == "nan":
        return []
    # skipinitialspace=True so ', "Obfuscation...' is treated as a quoted field
    return [l.strip().strip("'") for l in next(csv_mod.reader([s], skipinitialspace=True)) if l.strip()]

# Collect all unique raw labels
raw_labels = set()
for s in final_df["final"]:
    raw_labels.update(parse_final_labels(s))

print("Raw labels from final column:")
for l in sorted(raw_labels):
    print(f"  {l}")

Raw labels from final column:
  Appeal to (Strong) emotions
  Appeal to authority
  Appeal to fear/prejudice
  Bandwagon
  Black-and-white Fallacy/Dictatorship
  Causal Oversimplification
  Doubt
  Exaggeration/Minimisation
  Flag-waiving
  Glittering generalities (Virtue)
  Loaded Language
  Misrepresentation of Someone's Position (Straw Man)
  Name calling/Labeling
  Obfuscation, Intentional vagueness, Confusion
  Presenting Irrelevant Data (Red Herring)
  Reductio ad hitlerum
  Repetitions
  Slogans
  Smears
  Thought-terminating cliché
  Transfer

In [54]:
final_df

,image,labels_annotator1,labels_annotator2,final
0,image_0.jpg,['Smears'],"['Appeal to (Strong) Emotions', 'Flag-waving',...","Flag-waiving, Smears, Transfer"
1,image_1.jpg,['Whataboutism'],"['Appeal to (Strong) Emotions', 'Appeal to fea...","Smears, Transfer"
2,image_2.jpg,"['Causal Oversimplification', 'Smears']","['Appeal to (Strong) Emotions', 'Exaggeration/...","Exaggeration/Minimisation, Flag-waiving"
3,image_3.jpg,"['Doubt', 'Smears']","['Appeal to (Strong) Emotions', 'Doubt', 'Smea...","Doubt, Smears"
4,image_4.jpg,"['Appeal to fear/prejudice', 'Exaggeration/Min...","['Appeal to fear/prejudice', 'Exaggeration/Min...","Appeal to fear/prejudice, Smears, Exaggeration..."
...,...,...,...,...
195,image_195.jpg,['No Propaganda'],['No Propaganda'],No Propaganda
196,image_196.jpg,['No Propaganda'],['Appeal to (Strong) Emotions'],Appeal to (Strong) emotions
197,image_197.jpg,['No Propaganda'],['No Propaganda'],No Propaganda
198,image_198.jpg,['No Propaganda'],['No Propaganda'],No Propaganda
199,image_199.jpg,['No Propaganda'],['No Propaganda'],No Propaganda

In [55]:
# ── Map dirty labels → canonical using difflib ────────────────────────────────
# Re-define expected_labels (the original set was mutated by earlier get_label_mapping calls)
expected_labels_fresh = [
    'Appeal to (Strong) Emotions', 'Appeal to authority', 'Appeal to fear/prejudice',
    'Bandwagon', 'Black-and-white Fallacy/Dictatorship', 'Causal Oversimplification',
    'Doubt', 'Exaggeration/Minimisation', 'Flag-waving',
    'Glittering generalities (Virtue)', 'Loaded Language',
    "Misrepresentation of Someone's Position (Straw Man)", 'Name calling/Labeling',
    'Obfuscation, Intentional vagueness, Confusion',
    'Presenting Irrelevant Data (Red Herring)', 'Reductio ad hitlerum',
    'Repetition', 'Slogans', 'Smears', 'Thought-terminating cliché',
    'Transfer', 'Whataboutism',
]

final_label_mapping = get_label_mapping(sorted(raw_labels), list(expected_labels_fresh), cutoff=0.6)

print("Final label mapping:")
for old, new in sorted(final_label_mapping.items()):
    flag = " UNMAPPED" if new is None else ("" if old == new else " <- fixed")
    print(f"  {old!r:60s} -> {new!r}{flag}")

Final label mapping:
  'Appeal to (Strong) emotions'                                -> 'Appeal to (Strong) Emotions' <- fixed
  'Appeal to authority'                                        -> 'Appeal to authority'
  'Appeal to fear/prejudice'                                   -> 'Appeal to fear/prejudice'
  'Bandwagon'                                                  -> 'Bandwagon'
  'Black-and-white Fallacy/Dictatorship'                       -> 'Black-and-white Fallacy/Dictatorship'
  'Causal Oversimplification'                                  -> 'Causal Oversimplification'
  'Doubt'                                                      -> 'Doubt'
  'Exaggeration/Minimisation'                                  -> 'Exaggeration/Minimisation'
  'Flag-waiving'                                               -> 'Flag-waving' <- fixed
  'Glittering generalities (Virtue)'                           -> 'Glittering generalities (Virtue)'
  'Loaded Language'                                            -> 'Loaded Language'
  "Misrepresentation of Someone's Position (Straw Man)"        -> "Misrepresentation of Someone's Position (Straw Man)"
  'Name calling/Labeling'                                      -> 'Name calling/Labeling'
  'Obfuscation, Intentional vagueness, Confusion'              -> 'Obfuscation, Intentional vagueness, Confusion'
  'Presenting Irrelevant Data (Red Herring)'                   -> 'Presenting Irrelevant Data (Red Herring)'
  'Reductio ad hitlerum'                                       -> 'Reductio ad hitlerum'
  'Repetitions'                                                -> 'Repetition' <- fixed
  'Slogans'                                                    -> 'Slogans'
  'Smears'                                                     -> 'Smears'
  'Thought-terminating cliché'                                 -> 'Thought-terminating cliché'
  'Transfer'                                                   -> 'Transfer'

In [56]:
# ── Build results with final labels + OCR text, save JSONL ────────────────────
id_to_result = {r["image"]: r for r in results}

final_results = []
for _, row in final_df.iterrows():
    real_image = image_name_to_real.get(row["image"], row["image"])

    raw = parse_final_labels(row["final"])
    mapped = [final_label_mapping.get(l, l) for l in raw]
    mapped = [l for l in mapped if l is not None]

    existing = id_to_result.get(real_image, {})
    text = existing.get("text", "")

    final_results.append({
        "id": real_image.split(".")[0],
        "labels": mapped,
        "text": text,
        "image": real_image,
    })

print(f"Built {len(final_results)} records")
print(f"Example: {final_results[0]}")

out_path = "/home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/test.jsonl"
with open(out_path, "w") as f:
    for item in final_results:
        json.dump(item, f, ensure_ascii=False)
        f.write("\n")
print(f"Saved to {out_path}")

Built 200 records
Example: {'id': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig', 'labels': ['Flag-waving', 'Smears', 'Transfer'], 'text': '', 'image': 'csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig'}
Saved to /home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/test.jsonl

In [58]:
# ── Add OCR text from results to existing JSONL ──────────────────────────────
jsonl_path = "/home/nazara/Data2/DIPLOMA/datasets/ukrainian/annotations/test.jsonl"

with open(jsonl_path) as f:
    records = [json.loads(line) for line in f if line.strip()]

# Build lookup from results (which already has OCR text)
id_to_text = {r["id"]: r["text"] for r in results}

for item in records:
    if not item["image"].endswith(".jpg"):
        item["image"] = item["image"] + ".jpg"
    if not item["text"].strip():
        item["text"] = id_to_text.get(item["id"], "")

with open(jsonl_path, "w") as f:
    for item in records:
        json.dump(item, f, ensure_ascii=False)
        f.write("\n")

n_with_text = sum(1 for r in records if r["text"].strip())
print(f"Updated {len(records)} records ({n_with_text} with text)")

Updated 200 records (200 with text)

In [ ]:
import os 
import json 


path = "/home/nazara/Data2/DIPLOMA/datasets/translated/annotations/test_whole.jsonl"
test_data = []
with open(path, "r") as f:
    for line in f:
        obj = json.loads(line)
        if os.path.exists('/home/nazara/Data2/DIPLOMA/datasets/translated/images/' + obj['image']):
            test_data.append(obj)

In [ ]:
#save jsonl
with open('/home/nazara/Data2/DIPLOMA/datasets/translated/annotations/test.jsonl', 'w') as f:
    for item in test_data:
        json.dump(item, f)
        f.write('\n')

In [ ]:
annotators_df

,image,labels_annotator1,labels_annotator2
0,csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig.jpg,[Smears],"[Appeal to (Strong) Emotions, Flag-waving, Sme..."
1,csv_10nuP18xGKwhwzie8LQg1jJvQ7sEyBUNk.jpg,[Whataboutism],"[Appeal to (Strong) Emotions, Appeal to fear/p..."
2,csv_11FXDzESQrZpC5yqpUrKbsipXldf1owRH.jpg,"[Causal Oversimplification, Smears]","[Appeal to (Strong) Emotions, Exaggeration/Min..."
3,csv_12eKY_11DKhS3OJkRBe3Ik-w6IF0XoKHP.jpg,"[Doubt, Smears]","[Appeal to (Strong) Emotions, Doubt, Smears]"
4,csv_12vuewEZ3Dv50-FjDlCv4RFJpRr-EhPNZ.jpg,"[Appeal to fear/prejudice, Exaggeration/Minimi...","[Appeal to fear/prejudice, Exaggeration/Minimi..."
...,...,...,...
195,tg_5374.jpg,[No Propaganda],[No Propaganda]
196,tg_5375.jpg,[No Propaganda],[Appeal to (Strong) Emotions]
197,tg_5376.jpg,[No Propaganda],[No Propaganda]
198,tg_5379.jpg,[No Propaganda],[No Propaganda]
199,tg_5380.jpg,[No Propaganda],[No Propaganda]

In [ ]:
import shutil

AttributeError: module 'os' has no attribute 'copy'

In [ ]:
annotators_df

,image,labels_annotator1,labels_annotator2,image_name
0,csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig.jpg,[Smears],"[Appeal to (Strong) Emotions, Flag-waving, Sme...",image_0.jpg
1,csv_10nuP18xGKwhwzie8LQg1jJvQ7sEyBUNk.jpg,[Whataboutism],"[Appeal to (Strong) Emotions, Appeal to fear/p...",image_1.jpg
2,csv_11FXDzESQrZpC5yqpUrKbsipXldf1owRH.jpg,"[Causal Oversimplification, Smears]","[Appeal to (Strong) Emotions, Exaggeration/Min...",image_2.jpg
3,csv_12eKY_11DKhS3OJkRBe3Ik-w6IF0XoKHP.jpg,"[Doubt, Smears]","[Appeal to (Strong) Emotions, Doubt, Smears]",image_3.jpg
4,csv_12vuewEZ3Dv50-FjDlCv4RFJpRr-EhPNZ.jpg,"[Appeal to fear/prejudice, Exaggeration/Minimi...","[Appeal to fear/prejudice, Exaggeration/Minimi...",image_4.jpg
...,...,...,...,...
195,tg_5374.jpg,[No Propaganda],[No Propaganda],image_195.jpg
196,tg_5375.jpg,[No Propaganda],[Appeal to (Strong) Emotions],image_196.jpg
197,tg_5376.jpg,[No Propaganda],[No Propaganda],image_197.jpg
198,tg_5379.jpg,[No Propaganda],[No Propaganda],image_198.jpg
199,tg_5380.jpg,[No Propaganda],[No Propaganda],image_199.jpg

In [ ]:
import shutil
annotators_df['image_name'] = [f"image_{x}.jpg" for x in list(range(len(annotators_df)))]
for _, row in annotators_df.iterrows():
    image_name = row['image_name']
    source_path = f"./ukrainian/images/{row['image']}"
    target_path = f"./ukrainian/selection/{image_name}"
    shutil.copy(source_path, target_path)
annotators_df['image'] = annotators_df['image_name']
annotators_df.drop(columns=['image_name'], inplace=True)
annotators_df.to_csv("/home/nazara/Data2/DIPLOMA/datasets/ukrainian/selection/annotators.csv", index=False)

{0:                                               filename  \
 0    tg_5293_jpg.rf.6079fcdff12ba72161ccee81de7cbe7...
 1    csv_1cmjkZ8nBDuRrOEk4CzrF69nLdbIOw_yK_jpg.rf.9...
 2    tg_5365_jpg.rf.e7365586f7b40105a3b697902ec7f74...
 3    tg_5283_jpg.rf.0d35e8e61c4dcf661f9d666e19e487a...
 4    csv_1KXdSpbH06J7508iSvl9xeRvbZ3vXhF3E_jpg.rf.e...
 ..                                                 ...
 195  csv_1UTsSKtviwlAP0yIT6U5hbn1oTUgZsV46_jpg.rf.0...
 196  csv_1Py92xnYDI5ilr30qKDF1GIIx9ftRV5h-_jpg.rf.7...
 197  csv_16iNP31Z76-aUG4_3v2dVQXT6-vl5WvrT_jpg.rf.0...
 198  tg_5334_jpg.rf.0ab14c7ec2f0180549a7e103a8f87b0...
 199  csv_1yNAKOfqD7K-rC-y5zsEtYyuB3xMvXbdX_jpg.rf.c...

      Appeal to (Strong) Emotions  Appeal to fear/prejudice  Bandwagon  \
 0                              0                         0          0
 1                              1                         0          0
 2                              0                         1          1
 3                              0                         0          0
 4                              1                         0          0
 ..                           ...                       ...        ...
 195                            0                         0          0
 196                            0                         0          0
 197                            0                         0          0
 198                            0                         0          0
 199                            0                         0          0

      Black-and-white Fallacy/Dictatorship  Causal Oversimplification  Doubt  \
 0                                       0                          0      0
 1                                       0                          1      0
 2                                       0                          0      0
 3                                       0                          0      0
 4                                       0                          0      0
 ..                                    ...                        ...    ...
 195                                     0                          0      0
 196                                     0                          0      0
 197                                     0                          0      0
 198                                     0                          0      0
 199                                     0                          0      0

      Exaggeration/Minimisation  Flag-waving  Glittering generalities (Virtue)  \
 0                            0            0                                 0
 1                            0            0                                 0
 2                            0            1                                 0
 3                            0            0                                 0
 4                            0            1                                 0
 ..                         ...          ...                               ...
 195                          1            0                                 0
 196                          1            0                                 0
 197                          0            0                                 0
 198                          0            0                                 0
 199                          1            1                                 0

      ...  Obfuscation, Intentional vagueness, Confusion  \
 0    ...                                              0
 1    ...                                              0
 2    ...                                              0
 3    ...                                              0
 4    ...                                              0
 ..   ...                                            ...
 195  ...                                              0
 196  ...                                              0
 197  ...                                              0
 198  ...                                              0
 199  ...                                              0

      Presenting Irrelevant Data (Red Herring)  Reductio ad hitlerum  \
 0                                           0                     0
 1                                           0                     0
 2                                           0                     0
 3                                           0                     0
 4                                           0                     0
 ..                                        ...                   ...
 195                                         0                     0
 196                                         0                     0
 197                                         0                     0
 198                                         0                     0
 199                                         0                     0

      Repetition  Slogans  Smears  Thought-terminating cliché  Transfer  \
 0             0        0       0                           0         0
 1             0        0       0                           1         0
 2             0        0       0                           0         0
 3             0        0       0                           0         0
 4             0        0       0                           0         0
 ..          ...      ...     ...                         ...       ...
 195           0        0       0                           0         0
 196           0        0       0                           0         0
 197           0        0       0                           0         0
 198           0        0       0                           0         0
 199           0        0       0                           0         0

      Whataboutism  Appeal to authority
 0               0                    0
 1               0                    0
 2               0                    0
 3               0                    0
 4               0                    0
 ..            ...                  ...
 195             0                    0
 196             0                    0
 197             0                    0
 198             0                    0
 199             0                    0

 [200 rows x 24 columns],
 1:                                               filename  \
 0    csv_15Xl8UwDt1ZSFTNyzlZN6fMHpXEpYHQCk_jpg.rf.3...
 1    tg_5298_jpg.rf.28744676127f84fe13f08c19a3a5574...
 2    tg_5293_jpg.rf.3da6778288fea0879b260b835a93295...
 3    tg_5343_jpg.rf.a18607a43cedc67579a39a88a441ab4...
 4    csv_1bydWAdq0PijW8t3sPZEiQADZaaKDyVDk_jpg.rf.4...
 ..                                                 ...
 195  tg_5277_jpg.rf.c16f3385d13420322f3849707c543c8...
 196  tg_5269_jpg.rf.0ea96beabfc4687b6e9f1ec7773c6be...
 197  csv_1t46Km_iQzoXF3ExZYzThS_gfcQnLcEIa_jpg.rf.c...
 198  csv_1DtfA0h_xVyHPGp2LrNFyXpLdDiA8uaHs_jpg.rf.f...
 199  csv_1Z7YxQ36i1QBhEuQxmBUZ3HxnGFxPYExt_jpg.rf.8...

      Appeal to (Strong) Emotions  Appeal to authority  \
 0                              1                    0
 1                              0                    0
 2                              0                    0
 3                              0                    0
 4                              0                    0
 ..                           ...                  ...
 195                            0                    0
 196                            0                    0
 197                            0                    0
 198                            0                    0
 199                            0                    0

      Appeal to fear/prejudice  Bandwagon  \
 0                           0          0
 1                           0          0
 2                           0          0
 3                           0          0
 4                           0          0
 ..                        ...        ...
 195                         0          0
 196                         0          0
 197                         0          0
 198                         0          0
 199                         0          0

      Black-and-white Fallacy/Dictatorship  Causal Oversimplification  Doubt  \
 0                                       0                          1      0
 1                                       0                          0      0
 2                                       0                          0      0
 3                                       0                          0      0
 4                                       0                          0      0
 ..                                    ...                        ...    ...
 195                                     0                          0      0
 196                                     0                          0      0
 197                                     0                          0      0
 198                                     0                          0      0
 199                                     0                          0      0

      Exaggeration/Minimisation  Flag-waving  ...  No Propaganda  \
 0                            0            0  ...              0
 1                            0            0  ...              1
 2                            0            0  ...              1
 3                            0            0  ...              0
 4                            0            0  ...              0
 ..                         ...          ...  ...            ...
 195                          0            0  ...              1
 196                          0            0  ...              1
 197                          0            0  ...              1
 198                          0            1  ...              0
 199                          0            1  ...              0

      Obfuscation, Intentional vagueness, Confusion  \
 0                                                0
 1                                                0
 2                                                0
 3                                                0
 4                                                1
 ..                                             ...
 195                                              0
 196                                              0
 197                                              0
 198                                              0
 199                                              0

      Presenting Irrelevant Data (Red Herring)  Reductio ad hitlerum  Slogans  \
 0                                           0                     0        0
 1                                           0                     0        0
 2                                           0                     0        0
 3                                           0                     1        0
 4                                           0                     0        0
 ..                                        ...                   ...      ...
 195                                         0                     0        0
 196                                         0                     0        0
 197                                         0                     0        0
 198                                         0                     0        0
 199                                         0                     0        0

      Smears  Thought-terminating cliché  Transfer  Whataboutism  \
 0         0                           0         0             0
 1         0                           0         0             0
 2         0                           0         0             0
 3         1                           0         0             0
 4         1                           0         0             0
 ..      ...                         ...       ...           ...
 195       0                           0         0             0
 196       0                           0         0             0
 197       0                           0         0             0
 198       1                           0         0             0
 199       0                           0         0             0

      Appeal to authority
 0                      0
 1                      0
 2                      0
 3                      0
 4                      0
 ..                   ...
 195                    0
 196                    0
 197                    0
 198                    0
 199                    0

 [200 rows x 24 columns]}

In [ ]:
source_path

'./ukrainian/images/csv_10RGn0cWAS8GFV0dlIwylPDcbmJNfLAig.jpg'